const DEFAULT={version:2,name:'Inder',week:1,currentDay:'Monday',weightsOwned:[8,12,16,20,24,28,32],sessions:0,minutes:0,sets:0,completed:{},exerciseDone:{},history:[],logs:{},ratings:{}};
let state=loadState(),activeExercise=0,seconds=90,timerHandle=null,timerRunning=false,deferredPrompt=null;
function loadState(){try{const saved=JSON.parse(localStorage.getItem('kb-coach-v2')||'null');if(saved)return Object.assign({},DEFAULT,saved);const old=JSON.parse(localStorage.getItem('kb-simple')||'null');if(old){const migrated=JSON.parse(JSON.stringify(DEFAULT));migrated.week=old.week||1;migrated.currentDay=old.currentDay||'Monday';migrated.sessions=old.sessions||0;migrated.sets=old.totalSets||0;migrated.completed=old.completed||{};migrated.history=old.history||[];return migrated}}catch{}return JSON.parse(JSON.stringify(DEFAULT))}
function persist(quiet=false){localStorage.setItem('kb-coach-v2',JSON.stringify(state));render();if(!quiet)toast('Saved')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',1200)}
function dayKey(day=state.currentDay,week=state.week){return 'w'+week+'-'+day}function exKey(index,day=state.currentDay,week=state.week){return 'w'+week+'-'+day+'-'+index}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function selectDay(day){state.currentDay=day;persist(true)}
function availableWeights(ex){if(ex.weights.length===1&&ex.weights[0]===0)return[0];const filtered=ex.weights.filter(w=>state.weightsOwned.includes(w));return filtered.length?filtered:ex.weights}
function suggestedWeight(ex){if(ex.weights[0]===0)return 0;const available=availableWeights(ex),log=state.logs[state.currentDay+'-'+ex.name];let target=ex.defaultWeight;if(log){let i=available.indexOf(log.weight);if(log.rating==='easy'&&i>=0&&i<available.length-1)target=available[i+1];else if((log.rating==='hard'||log.rating==='pain')&&i>0)target=available[i-1];else if(available.includes(log.weight))target=log.weight}if(!available.includes(target))target=available.reduce((a,b)=>Math.abs(b-ex.defaultWeight)<Math.abs(a-ex.defaultWeight)?b:a,available[0]);return target}
function render(){const day=PROGRAM[state.currentDay];document.getElementById('weekLabel').textContent='Week '+state.week;document.getElementById('heroWeek').textContent=state.week;document.getElementById('heroTitle').textContent=day.title+' Day';document.getElementById('heroText').textContent=day.focus+'. '+day.exercises.length+' exercises planned for about '+day.duration+' minutes.';document.getElementById('sessions').textContent=state.sessions;document.getElementById('minutes').textContent=state.minutes;document.getElementById('setsLogged').textContent=state.sets;document.getElementById('streak').textContent=calculateStreak();const doneDays=Object.keys(PROGRAM).filter(d=>state.completed[dayKey(d)]).length,pct=Math.round(doneDays/5*100);document.getElementById('ringValue').textContent=pct+'%';document.getElementById('ring').style.background='conic-gradient(var(--accent) '+pct*3.6+'deg,#273548 '+pct*3.6+'deg)';renderDays();renderWorkout();renderLibrary();renderProgress();renderSettings();paintTimer()}
function calculateStreak(){if(!state.history.length)return 0;const dates=[...new Set(state.history.map(h=>h.date.slice(0,10)))].sort().reverse();let streak=0,cursor=new Date();cursor.setHours(0,0,0,0);for(const s of dates){const d=new Date(s+'T00:00:00'),diff=Math.round((cursor-d)/86400000);if(diff===0||diff===1){streak++;cursor=d}else break}return streak}
function renderDays(){const el=document.getElementById('days');el.innerHTML='';Object.entries(PROGRAM).forEach(([day,d])=>{const b=document.createElement('button');b.className='day'+(day===state.currentDay?' active':'');b.innerHTML='<b>'+day.slice(0,3)+'</b><small>'+(state.completed[dayKey(day)]?'Completed':d.title)+'</small>';b.onclick=()=>selectDay(day);el.appendChild(b)})}
function renderWorkout(){const d=PROGRAM[state.currentDay];document.getElementById('dayLabel').textContent=state.currentDay.toUpperCase();document.getElementById('dayTitle').textContent=d.title;document.getElementById('dayMeta').textContent=d.focus+' · '+d.duration+' min';document.getElementById('warmupList').innerHTML=d.warmup.map(x=>'<li>'+x+'</li>').join('');document.getElementById('cooldownList').innerHTML=d.cooldown.map(x=>'<li>'+x+'</li>').join('');const el=document.getElementById('exerciseList');el.innerHTML='';d.exercises.forEach((ex,i)=>{const done=!!state.exerciseDone[exKey(i)],w=suggestedWeight(ex);const row=document.createElement('div');row.className='exercise'+(done?' done':'');row.innerHTML='<div class="num">'+(i+1)+'</div><div><h4>'+ex.name+'</h4><div class="meta">'+ex.sets+' sets · '+ex.reps+' · '+(w===0?'Bodyweight':w+' kg')+'</div></div><div class="row-actions"><a class="mini video" target="_blank" rel="noopener" href="'+ex.video+'">Video</a><button class="mini done-btn '+(done?'on':'')+'" onclick="toggleExercise('+i+')">'+(done?'Done':'Complete')+'</button></div>';el.appendChild(row)})}
function toggleExercise(i){state.exerciseDone[exKey(i)]=!state.exerciseDone[exKey(i)];persist(true)}
function uniqueExercises(){const map={};Object.values(PROGRAM).forEach(d=>d.exercises.forEach(ex=>map[ex.name]=ex));return Object.values(map)}
function renderLibrary(){const q=(document.getElementById('librarySearch').value||'').toLowerCase(),el=document.getElementById('libraryGrid');el.innerHTML='';uniqueExercises().filter(ex=>ex.name.toLowerCase().includes(q)).forEach(ex=>{const c=document.createElement('div');c.className='card lib';c.innerHTML='<div class="art">🏋️</div><h3>'+ex.name+'</h3><p class="meta">'+ex.cue+'</p><div class="chips"><span class="chip">'+ex.sets+' sets</span><span class="chip">'+ex.rest+' sec rest</span></div><p class="meta"><b>Common mistakes:</b> '+ex.mistakes.join(', ')+'</p><a class="mini video" target="_blank" rel="noopener" href="'+ex.video+'">Watch technique</a>';el.appendChild(c)})}
function renderProgress(){const grid=document.getElementById('weekGrid');grid.innerHTML='';for(let w=1;w<=12;w++){const count=Object.keys(PROGRAM).filter(d=>state.completed[dayKey(d,w)]).length,c=document.createElement('div');c.className='weekcell'+(count===5?' complete':'')+(w===state.week?' current':'');c.innerHTML='<b>W'+w+'</b><small>'+count+'/5</small>';grid.appendChild(c)}const easy=Object.values(state.ratings).filter(v=>v==='easy').length,hard=Object.values(state.ratings).filter(v=>v==='hard').length,pain=Object.values(state.ratings).filter(v=>v==='pain').length;document.getElementById('coachReview').innerHTML='<p><b>Ready to increase:</b> '+easy+' exercise(s).</p><p><b>Keep lighter:</b> '+hard+' exercise(s).</p><p><b>Pain flags:</b> '+pain+'. Use substitutions and stop if pain continues.</p>';const list=document.getElementById('historyList');list.innerHTML='';if(!state.history.length){list.innerHTML='<div class="empty">No completed workouts yet.</div>'}else state.history.forEach(h=>{const r=document.createElement('div');r.className='history-item';r.innerHTML='<div><b>'+h.day+' · '+h.title+'</b><div class="meta">Week '+h.week+' · '+new Date(h.date).toLocaleDateString()+'</div></div><span class="chip">'+h.duration+' min</span>';list.appendChild(r)})}
function renderSettings(){const week=document.getElementById('weekSelect');if(!week.options.length){for(let i=1;i<=12;i++){const o=document.createElement('option');o.value=i;o.textContent='Week '+i;week.appendChild(o)}}week.value=state.week;document.getElementById('nameInput').value=state.name;const grid=document.getElementById('weightsGrid');grid.innerHTML='';[8,12,16,20,24,28,32,36,40].forEach(w=>{const b=document.createElement('button');b.className='weight-btn'+(state.weightsOwned.includes(w)?' selected':'');b.textContent=w+' kg';b.dataset.weight=w;b.onclick=()=>b.classList.toggle('selected');grid.appendChild(b)})}
function saveSettings(){state.week=Number(document.getElementById('weekSelect').value);state.name=document.getElementById('nameInput').value.trim()||'Inder';state.weightsOwned=[...document.querySelectorAll('#weightsGrid .weight-btn.selected')].map(b=>Number(b.dataset.weight)).sort((a,b)=>a-b);persist()}
function startGuidedWorkout(){activeExercise=0;renderGuided();document.getElementById('guidedModal').classList.add('open')}
function closeGuidedWorkout(){document.getElementById('guidedModal').classList.remove('open')}
function renderGuided(){const d=PROGRAM[state.currentDay],ex=d.exercises[activeExercise],w=suggestedWeight(ex);document.getElementById('modalDay').textContent=state.currentDay.toUpperCase()+' · EXERCISE '+(activeExercise+1)+' OF '+d.exercises.length;document.getElementById('modalTitle').textContent=ex.name;document.getElementById('coachCue').innerHTML='<b>Coach cue:</b> '+ex.cue+'<br><span class="meta">Suggested weight: '+(w===0?'Bodyweight':w+' kg')+' · Rest: '+ex.rest+' sec</span>';document.getElementById('mistakes').innerHTML=ex.mistakes.map(x=>'<li>'+x+'</li>').join('');document.getElementById('substitutions').innerHTML=ex.subs.map(x=>'<li>'+x+'</li>').join('');document.getElementById('videoLink').href=ex.video;const steps=document.getElementById('steps');steps.innerHTML='';d.exercises.forEach((_,i)=>{const b=document.createElement('button');b.className='step'+(i===activeExercise?' active':'');b.textContent=i+1;b.onclick=()=>{activeExercise=i;renderGuided()};steps.appendChild(b)});const sets=document.getElementById('setList');sets.innerHTML='';const available=availableWeights(ex);for(let i=0;i<ex.sets;i++){const row=document.createElement('div');row.className='setrow';row.innerHTML='<b>Set '+(i+1)+'</b><select class="set-weight">'+available.map(v=>'<option value="'+v+'" '+(v===w?'selected':'')+'>'+(v===0?'Bodyweight':v+' kg')+'</option>').join('')+'</select><input class="set-reps" value="'+ex.reps+'"><button class="mini done-btn" onclick="markSet(this)">Mark</button>';sets.appendChild(row)}document.getElementById('modalProgress').textContent=(activeExercise+1)+' of '+d.exercises.length+' exercises';document.getElementById('modalFill').style.width=((activeExercise+1)/d.exercises.length*100)+'%';setTimer(ex.rest)}
function markSet(btn){if(btn.classList.contains('on'))return;btn.classList.add('on');btn.textContent='Done';state.sets++;persist(true);if(navigator.vibrate)navigator.vibrate(80);const ex=PROGRAM[state.currentDay].exercises[activeExercise];setTimer(ex.rest);if(!timerRunning)toggleTimer()}
function rateExercise(rating){const ex=PROGRAM[state.currentDay].exercises[activeExercise],key=state.currentDay+'-'+ex.name;state.logs[key]={weight:suggestedWeight(ex),rating,date:new Date().toISOString()};state.ratings[key]=rating;persist(true);toast(rating==='easy'?'Next workout weight increased':rating==='hard'?'Next workout weight reduced':rating==='pain'?'Use a substitution and stop if pain continues':'Performance saved')}
function nextExercise(){const d=PROGRAM[state.currentDay];state.exerciseDone[exKey(activeExercise)]=true;if(activeExercise<d.exercises.length-1){activeExercise++;persist(true);renderGuided()}else completeWorkout()}
function previousExercise(){if(activeExercise>0){activeExercise--;renderGuided()}}
function completeWorkout(){const key=dayKey();if(!state.completed[key]){const d=PROGRAM[state.currentDay];state.completed[key]=true;state.sessions++;state.minutes+=d.duration;state.history.unshift({date:new Date().toISOString(),day:state.currentDay,title:d.title,week:state.week,duration:d.duration})}persist();closeGuidedWorkout();toast('Workout completed')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kettlebell-coach-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function importData(file){const r=new FileReader();r.onload=()=>{try{state=Object.assign({},DEFAULT,JSON.parse(r.result));persist();toast('Backup imported')}catch{toast('Invalid backup file')}};r.readAsText(file)}
function resetData(){if(confirm('Reset all workout data?')){state=JSON.parse(JSON.stringify(DEFAULT));persist()}}
function setTimer(s){seconds=s;paintTimer()}function paintTimer(){document.getElementById('timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}function toggleTimer(){if(timerRunning){clearInterval(timerHandle);timerRunning=false;document.getElementById('timerBtn').textContent='Start';return}timerRunning=true;document.getElementById('timerBtn').textContent='Pause';timerHandle=setInterval(()=>{seconds--;paintTimer();if(seconds<=0){clearInterval(timerHandle);timerRunning=false;document.getElementById('timerBtn').textContent='Start';if(navigator.vibrate)navigator.vibrate([150,80,150]);toast('Rest complete')}},1000)}function resetTimer(){clearInterval(timerHandle);timerRunning=false;seconds=90;document.getElementById('timerBtn').textContent='Start';paintTimer()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('Use Share, then Add to Home Screen')};document.getElementById('librarySearch').addEventListener('input',renderLibrary);document.getElementById('importFile').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0])});if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{});render();