const PROGRAM={
Monday:{title:'Strength',focus:'Full-body strength',duration:50,warmup:['Hip hinge drill × 10','Bodyweight squat × 10','Arm circles × 20','Light swings × 15'],cooldown:['Hip flexor stretch 45 sec/side','Child’s pose 60 sec','Deep breathing 2 min'],exercises:[
{name:'Goblet Squat',sets:5,reps:'5',rest:90,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Keep the bell tight to your chest. Sit between your hips.',mistakes:['Heels lifting','Knees collapsing inward','Rounding the lower back'],subs:['Box squat','Bodyweight squat','Supported split squat'],video:'https://www.youtube.com/results?search_query=dan+john+goblet+squat'},
{name:'Single Arm Overhead Press',sets:5,reps:'5 each arm',rest:90,defaultWeight:16,weights:[8,12,16,20,24],cue:'Brace your core and press without leaning back.',mistakes:['Rib flare','Bent wrist','Pressing away from the body'],subs:['Half-kneeling press','Floor press','Push press'],video:'https://www.youtube.com/results?search_query=single+arm+kettlebell+overhead+press'},
{name:'Single Arm Row',sets:4,reps:'8 each arm',rest:75,defaultWeight:20,weights:[12,16,20,24,28,32],cue:'Pull toward your hip while keeping your back flat.',mistakes:['Twisting the torso','Shrugging','Pulling toward the chest'],subs:['Supported row','Band row','Renegade row from knees'],video:'https://www.youtube.com/results?search_query=single+arm+kettlebell+row'},
{name:'Suitcase Carry',sets:4,reps:'40 m each side',rest:60,defaultWeight:24,weights:[16,20,24,28,32],cue:'Stay tall and keep your shoulders level.',mistakes:['Leaning toward the bell','Rushing','Short uneven steps'],subs:['March in place','Farmer hold','Rack carry'],video:'https://www.youtube.com/results?search_query=suitcase+carry+kettlebell'},
{name:'Plank',sets:3,reps:'45 to 60 sec',rest:60,defaultWeight:0,weights:[0],cue:'Squeeze your glutes and keep your ribs down.',mistakes:['Hips sagging','Head dropping','Holding your breath'],subs:['Knee plank','Dead bug','Bird dog'],video:'https://www.youtube.com/results?search_query=proper+plank+form'}]},
Tuesday:{title:'Conditioning',focus:'Endurance and work capacity',duration:40,warmup:['March in place 60 sec','Hip hinge drill × 10','Glute bridge × 12','Light swings × 15'],cooldown:['Hamstring stretch 45 sec/side','Figure-four stretch 45 sec/side','Deep breathing 2 min'],exercises:[
{name:'Kettlebell Swing',sets:10,reps:'20',rest:45,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Hinge, snap your hips, and let the bell float.',mistakes:['Squatting the swing','Lifting with the arms','Leaning back at lockout'],subs:['Kettlebell deadlift','Hike-pass drill','Hip bridge'],video:'https://www.youtube.com/results?search_query=mark+wildman+kettlebell+swing'},
{name:'Push-up',sets:4,reps:'10 to 15',rest:60,defaultWeight:0,weights:[0],cue:'Keep a straight line from shoulders to heels.',mistakes:['Elbows flaring','Hips sagging','Shallow range'],subs:['Incline push-up','Knee push-up','Floor press'],video:'https://www.youtube.com/results?search_query=push+up+proper+form'},
{name:'Goblet Squat',sets:3,reps:'15',rest:75,defaultWeight:20,weights:[12,16,20,24,28],cue:'Stay tall and keep your knees tracking over your toes.',mistakes:['Heels lifting','Rounding the back','Knees collapsing'],subs:['Box squat','Bodyweight squat','Reverse lunge'],video:'https://www.youtube.com/results?search_query=dan+john+goblet+squat'},
{name:'Mountain Climber',sets:3,reps:'30 sec',rest:45,defaultWeight:0,weights:[0],cue:'Drive the knees without bouncing your hips.',mistakes:['Hips too high','Short range','Shoulders behind hands'],subs:['Slow mountain climber','Standing knee drive','Marching plank'],video:'https://www.youtube.com/results?search_query=mountain+climber+exercise'},
{name:'Dead Bug',sets:3,reps:'12 each side',rest:45,defaultWeight:0,weights:[0],cue:'Keep your lower back pressed into the floor.',mistakes:['Back arching','Moving too fast','Holding your breath'],subs:['Heel taps','Bird dog','Knee plank'],video:'https://www.youtube.com/results?search_query=dead+bug+exercise'}]},
Wednesday:{title:'Upper Body',focus:'Pressing and pulling strength',duration:50,warmup:['Shoulder circles × 20','Scapular push-up × 10','Halo × 8 each direction','Light row × 10/side'],cooldown:['Chest stretch 45 sec/side','Lat stretch 45 sec/side','Deep breathing 2 min'],exercises:[
{name:'Single Arm Floor Press',sets:4,reps:'8 each arm',rest:75,defaultWeight:16,weights:[8,12,16,20,24],cue:'Pause your upper arm on the floor and press smoothly.',mistakes:['Bent wrist','Elbow too wide','Bouncing off the floor'],subs:['Incline push-up','Push-up','Neutral-grip press'],video:'https://www.youtube.com/results?search_query=kettlebell+floor+press'},
{name:'Single Arm Row',sets:4,reps:'10 each arm',rest:75,defaultWeight:20,weights:[12,16,20,24,28,32],cue:'Keep your shoulders square to the floor.',mistakes:['Twisting','Shrugging','Rounding the back'],subs:['Supported row','Band row','Renegade row from knees'],video:'https://www.youtube.com/results?search_query=single+arm+kettlebell+row'},
{name:'Half Kneeling Press',sets:3,reps:'10 each arm',rest:75,defaultWeight:16,weights:[8,12,16,20],cue:'Tuck your pelvis and press without leaning.',mistakes:['Arching the back','Losing balance','Pressing outward'],subs:['Seated press','Floor press','Push press'],video:'https://www.youtube.com/results?search_query=half+kneeling+kettlebell+press'},
{name:'Hammer Curl',sets:3,reps:'12 each arm',rest:60,defaultWeight:12,weights:[8,12,16],cue:'Keep your elbows close to your sides.',mistakes:['Swinging the bell','Leaning back','Moving the elbow'],subs:['Two-hand curl','Isometric hold','Band curl'],video:'https://www.youtube.com/results?search_query=kettlebell+hammer+curl'},
{name:'Turkish Get-up',sets:3,reps:'1 each side',rest:90,defaultWeight:12,weights:[8,12,16,20],cue:'Move one step at a time and keep your eyes on the bell.',mistakes:['Rushing','Losing wrist alignment','Skipping positions'],subs:['Half get-up','No-weight get-up','Tall sit-up'],video:'https://www.youtube.com/results?search_query=mark+wildman+turkish+get+up'}]},
Thursday:{title:'Lower Body',focus:'Leg strength and posterior chain',duration:50,warmup:['Ankle rocks × 10/side','Glute bridge × 12','Bodyweight split squat × 8/side','Light swings × 15'],cooldown:['Quad stretch 45 sec/side','Hamstring stretch 45 sec/side','Calf stretch 45 sec/side'],exercises:[
{name:'Goblet Squat',sets:5,reps:'8',rest:90,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Brace before each rep and drive through your full foot.',mistakes:['Knees collapsing','Heels lifting','Losing your brace'],subs:['Box squat','Bodyweight squat','Supported split squat'],video:'https://www.youtube.com/results?search_query=dan+john+goblet+squat'},
{name:'Bulgarian Split Squat',sets:3,reps:'10 each leg',rest:90,defaultWeight:16,weights:[8,12,16,20,24],cue:'Drop straight down and keep your front heel planted.',mistakes:['Front knee collapsing','Unstable rear foot','Leaning too far'],subs:['Reverse lunge','Supported split squat','Step-up'],video:'https://www.youtube.com/results?search_query=bulgarian+split+squat+kettlebell'},
{name:'Single Leg Romanian Deadlift',sets:3,reps:'10 each leg',rest:75,defaultWeight:16,weights:[8,12,16,20,24],cue:'Reach the free leg back while keeping your hips square.',mistakes:['Opening the hips','Rounding the back','Too much knee bend'],subs:['Kickstand deadlift','Two-leg Romanian deadlift','Supported hinge'],video:'https://www.youtube.com/results?search_query=single+leg+romanian+deadlift+kettlebell'},
{name:'Kettlebell Swing',sets:5,reps:'20',rest:60,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Finish tall and keep your shoulders relaxed.',mistakes:['Squatting','Arm lifting','Leaning back at lockout'],subs:['Kettlebell deadlift','Hike-pass drill','Hip bridge'],video:'https://www.youtube.com/results?search_query=mark+wildman+kettlebell+swing'},
{name:'Side Plank',sets:3,reps:'30 sec each side',rest:45,defaultWeight:0,weights:[0],cue:'Keep your hips high and your body in one line.',mistakes:['Hips dropping','Rotating forward','Neck strain'],subs:['Knee side plank','Suitcase hold','Bird dog'],video:'https://www.youtube.com/results?search_query=side+plank+exercise'}]},
Friday:{title:'Full Body',focus:'Power and conditioning',duration:45,warmup:['March in place 60 sec','Hip hinge drill × 10','Rack hold 20 sec/side','Light clean × 5/side'],cooldown:['Hip flexor stretch 45 sec/side','Lat stretch 45 sec/side','Deep breathing 2 min'],exercises:[
{name:'Single Arm Clean',sets:5,reps:'5 each arm',rest:30,defaultWeight:20,weights:[8,12,16,20,24],cue:'Keep the bell close and receive it softly.',mistakes:['Bell slamming the forearm','Wide arc','Pulling too early'],subs:['Dead clean','High pull','Rack deadlift'],video:'https://www.youtube.com/results?search_query=single+arm+kettlebell+clean'},
{name:'Push Press',sets:5,reps:'5 each arm',rest:30,defaultWeight:16,weights:[8,12,16,20,24],cue:'Use a shallow dip and strong leg drive.',mistakes:['Deep squat','Soft lockout','Leaning back'],subs:['Strict press','Half-kneeling press','Floor press'],video:'https://www.youtube.com/results?search_query=single+arm+kettlebell+push+press'},
{name:'Goblet Squat',sets:5,reps:'10',rest:30,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Stay tall and control the bottom position.',mistakes:['Rushing','Heels lifting','Knees collapsing'],subs:['Box squat','Bodyweight squat','Reverse lunge'],video:'https://www.youtube.com/results?search_query=dan+john+goblet+squat'},
{name:'Kettlebell Swing',sets:5,reps:'15',rest:30,defaultWeight:24,weights:[12,16,20,24,28,32],cue:'Drive with your hips and keep your shoulders relaxed.',mistakes:['Squatting','Lifting with the arms','Overextending the back'],subs:['Kettlebell deadlift','Hike-pass drill','Hip bridge'],video:'https://www.youtube.com/results?search_query=mark+wildman+kettlebell+swing'},
{name:'Reverse Lunge',sets:5,reps:'5 each leg',rest:120,defaultWeight:16,weights:[8,12,16,20,24],cue:'Step back softly and drive through the front foot.',mistakes:['Front heel lifting','Knee collapsing','Stepping too narrow'],subs:['Supported split squat','Step-up','Bodyweight reverse lunge'],video:'https://www.youtube.com/results?search_query=reverse+lunge+kettlebell'}]}}